services:
  - type: web
    name: ai-aggregator
    env: python
    buildCommand: ""
    startCommand: uvicorn ai_aggregator_backend:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
